### ISSUE TITLE
in https://paperswithcode.com/paper/scalable-bayesian-rule-lists mistakenly given a link to this code

### ISSUE THREAD

**Issue by Sandy4321** [nlarusstone/corels#6]
in https://paperswithcode.com/paper/scalable-bayesian-rule-lists mistakenly given a link to this code

in any case how different / better your paper/ code  from Scalable Bayesian Rule Lists

**Comment by jamesmyatt** [comment]
https://github.com/Hongyuy/sbrlmod?

**Comment by Sandy4321** [comment]
great so how different corels from sbrlmod is ?
I form sbrlmod  githib
https://github.com/Hongyuy/sbrlmod/issues/6
for 1 year not answered issue 
Memory leak #6
so 
sbrlmod is not supported?
but how it is performance wise corels vs sbrlmod??

**Comment by nlarusstone** [comment]
Hi, 

I can't comment on sbrlmod being supported or not because I don't maintain that repository. However, one of the key differences between CORELS and sbrlmod is that CORELS gives a guarantee of optimality. That means the rule list generated by CORELS is the best rule list for that set of rules and regularization. sblrmod gives no such guarantee.

Performance-wise, sbrlmod is likely faster since it gives no such guarantee. However, depending on the size of your problem, you may prefer to use CORELS for its optimality guarantees.
